version: "3.8"

services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "${REDIS_PORT:-6379}:6379"
    environment:
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_KEY=${REDIS_KEY}
    volumes:
      - redis-data:/data

  codepush-server:
    build: .
    ports:
      - "${PORT:-8443}:8443"
    environment:
      - NODE_ENV=${NODE_ENV:-development}
      - REDIS_HOST=redis
      - REDIS_PORT=${REDIS_PORT:-6379}
    depends_on:
      - redis
    volumes:
      - .:/app
      - /app/node_modules

volumes:
  redis-data:
